export const GOLDEN_SOUP_QUOTES = Object.freeze([
    // [Geek Romantic]
    { category: 'Geek Romantic', cn: '我在变量之间藏了心事，在函数里练习温柔。', en: 'I hide my feelings between variables and practice tenderness in functions.' },
    { category: 'Geek Romantic', cn: '物理说光有路径，我说你有坐标。', en: 'Physics says light has a path; I say you have coordinates.' },
    { category: 'Geek Romantic', cn: '如果宇宙有注释，我想那行一定写着"继续热爱"。', en: 'If the universe had comments, one line would read: keep loving.' },
    { category: 'Geek Romantic', cn: '在离散与连续之间，我选择把你插值成永恒。', en: 'Between discrete and continuous, I interpolate you into eternity.' },
    { category: 'Geek Romantic', cn: '当程序跑通的那一刻，世界短暂地变得诚实。', en: 'The moment the program runs, the world becomes honest for a while.' },
    { category: 'Geek Romantic', cn: '我把想念压进压缩包，解压时全是你。', en: 'I zip up my longing, and when unzipped, it is all you.' },

    // [Humorous Satire]
    { category: 'Humorous Satire', cn: 'Bug 从不下班，它只是换个时间提醒你谦卑。', en: 'Bugs never clock out; they just remind you to stay humble at new hours.' },
    { category: 'Humorous Satire', cn: '我不是修复了问题，我只是把问题移到了别人看不见的地方。', en: 'I did not fix the issue; I moved it where no one can see it.' },
    { category: 'Humorous Satire', cn: '改需求最快的方法：先说"这很简单"。', en: 'The fastest way to trigger requirement changes is to say "this is easy."' },
    { category: 'Humorous Satire', cn: '加班不是热爱，是与未知报错进行深夜谈判。', en: 'Overtime is not passion; it is midnight negotiation with unknown errors.' },
    { category: 'Humorous Satire', cn: '我有两种心情：在修 Bug，和在等下一个 Bug。', en: 'I have two moods: fixing a bug, and waiting for the next one.' },
    { category: 'Humorous Satire', cn: '我的人生就像没写 Readme 的项目，全靠瞎猜。', en: 'My life is like a project without a Readme; it\'s all guesswork.' },

    // [Disillusioned]
    { category: 'Disillusioned', cn: '成年人的崩溃，通常发生在"加载中"。', en: 'Adult breakdown often happens during "loading."' },
    { category: 'Disillusioned', cn: '后来我明白，很多努力只是延迟失败。', en: 'Later I learned many efforts merely delay failure.' },
    { category: 'Disillusioned', cn: '生活像未处理异常，出现时从不提前通知。', en: 'Life is an unhandled exception: it never announces itself.' },
    { category: 'Disillusioned', cn: '我把希望设成常量，现实总在运行时改值。', en: 'I set hope as a constant; reality mutates it at runtime.' },
    { category: 'Disillusioned', cn: '深夜最难的不是问题，是再也不相信答案。', en: 'At night, the hardest thing is not the problem but losing faith in answers.' },
    { category: 'Disillusioned', cn: '看起来我在进步，其实只是更会掩饰疲惫。', en: 'It looks like progress; I just got better at hiding exhaustion.' },
    { category: 'Disillusioned', cn: '梦想没有消失，它只是被账单重命名了。', en: 'Dreams did not disappear; they were renamed as bills.' },
    { category: 'Disillusioned', cn: '我依旧准时起床，只是再也不期待早晨。', en: 'I still wake up on time, I just no longer expect mornings.' },
    { category: 'Disillusioned', cn: '努力像回车键，按下去不一定有回响。', en: 'Effort is like pressing Enter: no guarantee of response.' },
    { category: 'Disillusioned', cn: '有些路走久了，不是到达，是麻木。', en: 'Some long roads lead not to arrival but numbness.' },
    { category: 'Disillusioned', cn: '有些事不是坚持就有结果，比如死掉的链接。', en: 'Some things don\'t yield results through persistence, like dead links.' },
    { category: 'Disillusioned', cn: '世界并没有针对你，它只是根本不在意你。', en: 'The world isn\'t targeting you; it simply doesn\'t care about you at all.' },
    { category: 'Disillusioned', cn: '我们都在等待一个不复存在的备份。', en: 'We are all waiting for a backup that no longer exists.' },
    { category: 'Disillusioned', cn: '所谓的成长，就是学会了给所有的失望打补丁。', en: 'Growth is learning how to patch all your disappointments.' },
    { category: 'Disillusioned', cn: '梦想破灭的声音，还没有键盘敲击声大。', en: 'The sound of dreams shattering is quieter than a keystroke.' },
    { category: 'Disillusioned', cn: '我试过格式化人生，可硬件已经老化了。', en: 'I tried to format my life, but the hardware is already aging.' },
    { category: 'Disillusioned', cn: '别谈未来，现在的我也只是在超负荷运转。', en: 'Don\'t talk about the future; even my current self is running at overload.' },
    { category: 'Disillusioned', cn: '有些报错可以修复，有些遗憾只能归档。', en: 'Some errors can be fixed; some regrets can only be archived.' },
    { category: 'Disillusioned', cn: '原以为自己是主角，结果只是个背景进程。', en: 'I thought I was the main process, but I\'m just a background task.' },
    { category: 'Disillusioned', cn: '时间带走的不仅是青春，还有对报错的耐心。', en: 'Time takes not only youth, but also patience for error messages.' },
    { category: 'Disillusioned', cn: '生活没有撤销键，只有不停增加的 Readonly。', en: 'Life has no Undo; only ever-increasing Readonly status.' },
    { category: 'Disillusioned', cn: '所谓的避风港，不过是延迟了风暴的到达。', en: 'A safe harbor merely delays the arrival of the storm.' },
    { category: 'Disillusioned', cn: '我们终将变成自己曾经最讨厌的那种代码。', en: 'We will eventually become the kind of code we once hated most.' },
    { category: 'Disillusioned', cn: '希望是消耗品，而我早已透支。', en: 'Hope is a consumable, and I am long since overdrawn.' },
    { category: 'Disillusioned', cn: '看窗外的天黑了又亮，代码还是原来的模样。', en: 'Watching the sky turn dark then bright; the code remains unchanged.' },
    { category: 'Disillusioned', cn: '所谓的诗和远方，都被困在了 15 寸的屏幕里。', en: 'What we call poetry and far lands are trapped in a 15-inch screen.' },
    { category: 'Disillusioned', cn: '有些努力只是为了证明：我真的不行。', en: 'Some efforts only serve to prove: I really can\'t do it.' },
    { category: 'Disillusioned', cn: '在这个充满随机性的世界里，稳定才是一种错觉。', en: 'In this world full of randomness, stability is the true illusion.' },
    { category: 'Disillusioned', cn: '所谓的救赎，不过是换了一个更舒适的牢笼。', en: 'What we call redemption is just switching to a more comfortable cage.' },
    { category: 'Disillusioned', cn: '我以为我在追逐梦想，结果只是被它牵着走。', en: 'I thought I was chasing dreams, but I was just being led by them.' },
    { category: 'Disillusioned', cn: '有些人不是不努力，而是努力了也没用。', en: 'Some people are not unmotivated; they just put effort into things that don\'t work.' },
    { category: 'Disillusioned', cn: '我以为时间会治愈一切，结果只是让一切变得麻木。', en: 'I thought time would heal everything, but it just makes everything numb.' },
    { category: 'Disillusioned', cn: '生活没有彩蛋，只有不断出现的隐藏 Bug。', en: 'Life has no Easter eggs, only continuously emerging hidden bugs.' },
    { category: 'Disillusioned', cn: '所谓的坚持，不过是对失败的习惯性容忍。', en: 'What we call persistence is just habitual tolerance for failure.' },
    { category: 'Disillusioned', cn: '我学会了微笑，因为解释没有预算', en: 'I learned to smile because explanations have no budget.' },
    { category: 'Disillusioned', cn: '有些人不是不在意你，而是根本没有把你放在心上。', en: 'Some people don\'t not care about you; they just never put you in their heart at all.' },
    { category: 'Disillusioned', cn: '我以为我在创造未来，结果只是被时代淘汰了。', en: 'I thought I was creating the future, but I was just being eliminated by the times.' },
    { category: 'Disillusioned', cn: '有些人不是不爱了，而是根本没爱过。', en: 'Some people don\'t stop loving; they just never loved in the first place.' },
    { category: 'Disillusioned', cn: '我以为我在追求自由，结果只是被另一个牢笼锁住了。', en: 'I thought I was pursuing freedom, but I was just locked in another cage.' },
    { category: 'Disillusioned', cn: '有些人不是不重要，而是根本没有存在过。', en: 'Some people are not unimportant; they just never existed at all.' },
    { category: 'Disillusioned', cn: '我以为我在寻找意义，结果只是被无意义淹没了。', en: 'I thought I was searching for meaning, but I was just drowned in meaninglessness.' },
    { category: 'Disillusioned', cn: '有些人不是不珍惜你，而是根本没有把你当回事。', en: 'Some people don\'t not cherish you; they just never took you seriously at all.' },
    { category: 'Disillusioned', cn: '我以为我在追逐梦想，结果只是被现实追着跑了。', en: 'I thought I was chasing dreams, but I was just being chased by reality.' },
    { category: 'Disillusioned', cn: '你以为别人赢在天赋，其实他们只是比你更早接受了现实。', en: 'You think others win by talent; they just accepted reality earlier than you did.' },
    { category: 'Disillusioned', cn: '努力不会骗人，但努力的方向会。', en: 'Effort doesn’t lie, but the direction of effort does.' },
    { category: 'Disillusioned', cn: '你以为是起点不公平，其实是终点根本不等你。', en: 'You think the start is unfair; the truth is the finish line isn’t waiting for you.' },
    { category: 'Disillusioned', cn: '失败不可怕，可怕的是你连失败的资格都没有。', en: 'Failure isn’t scary; not even qualifying to fail is.' },
    { category: 'Disillusioned', cn: '你不是不优秀，只是你的优秀没人需要。', en: 'You’re not incapable; your capability just isn’t needed.' },
    { category: 'Disillusioned', cn: '世界不是不公平，而是根本没打算公平。', en: 'The world isn’t unfair; it was never meant to be fair.' },
    { category: 'Disillusioned', cn: '你以为你在选择，其实只是被筛选。', en: 'You think you’re choosing; you’re just being filtered.' },
    { category: 'Disillusioned', cn: '有些门不是没敲开，是从一开始就没给你钥匙。', en: 'Some doors weren’t unopened; you were never given a key.' },
    { category: 'Disillusioned', cn: '努力不一定有回报，但不努力，一定很轻松。', en: 'Effort doesn\'t necessarily bring rewards, but not trying is definitely easy.' },
    { category: 'Disillusioned', cn: '你拼尽全力的上限，不过是别人的起点。', en: 'The upper limit of your best efforts is just the starting point of others.' },
    { category: 'Disillusioned', cn: '时间不是解药，是麻药，醒了之后，疼得更狠。', en: 'Time is not an antidote, but an anesthetic; when you wake up, it hurts even more.' },
    { category: 'Disillusioned', cn: '所谓希望，不过是让你多熬一会儿的谎言。', en: 'The so-called hope is just a lie that makes you endure a little longer.' },
    { category: 'Disillusioned', cn: '你以为的逆袭，不过是命运偶尔的施舍，转瞬即逝。', en: 'The counterattack you think is just an occasional alms from fate, fleeting.' },
    { category: 'Disillusioned', cn: '善良没用，你得漂亮，得有钱，得够狠。', en: 'Kindness is useless; you have to be beautiful, rich, and ruthless enough.' },
    { category: 'Disillusioned', cn: '有些人努力，是为了活着；有些人活着，不用努力。', en: 'Some people work hard just to live; some people live without having to work hard.' },
    { category: 'Disillusioned', cn: '我以为熬过去就好了，没想到熬过去，还有更难的。', en: 'I thought getting through it would be okay, but I didn\'t expect that after getting through it, there would be harder things.' },
    { category: 'Disillusioned', cn: '生活的真相：你越想要什么，就越得不到什么。', en: 'The truth of life: the more you want something, the more you can\'t get it.' },
    { category: 'Disillusioned', cn: '所谓成长，就是从满怀期待，变成麻木不仁。', en: 'The so-called growth is from full of expectations to numbness.' },
    { category: 'Disillusioned', cn: '你掏心掏肺对待的人，正在背后笑话你的天真。', en: 'The person you treat wholeheartedly is laughing at your naivety behind your back.' },
    { category: 'Disillusioned', cn: '努力改变命运，不过是安慰底层人的自我欺骗。', en: 'Working hard to change fate is just self-deception to comfort people at the bottom.' },
    { category: 'Disillusioned', cn: '我以为我很特别，原来只是芸芸众生里，最普通的炮灰。', en: 'I thought I was special, but it turns out I\'m just the most ordinary cannon fodder among all living beings.' },
    { category: 'Disillusioned', cn: '承诺都是用来打破的，深情都是用来辜负的。', en: 'Promises are all meant to be broken, and deep affection is all meant to be let down.' },
    { category: 'Disillusioned', cn: '你越懂事，越没人疼；越迁就，越受委屈。', en: 'The more sensible you are, the less someone cares about you; the more you accommodate, the more wronged you are.' },
    { category: 'Disillusioned', cn: '生活没有退路，只有绝路，要么熬，要么死。', en: 'Life has no retreat, only a dead end; either endure or die.' },
    { category: 'Disillusioned', cn: '有些人不是不优秀，是优秀错了地方，一文不值。', en: 'Some people are not unexcellent; they are excellent in the wrong place, worth nothing.' },
    { category: 'Disillusioned', cn: '我以为坚持就能看到光，结果只看到了无尽的黑暗。', en: 'I thought persistence would let me see the light, but I only saw endless darkness.' },
    { category: 'Disillusioned', cn: '所谓公平，就是强者制定规则，弱者被迫服从。', en: 'The so-called fairness is that the strong make the rules, and the weak are forced to obey.' },
    { category: 'Disillusioned', cn: '你付出的所有真心，最后都变成了别人的笑话。', en: 'All the sincerity you gave finally turned into a joke of others.' },
    { category: 'Disillusioned', cn: '努力的意义，就是让你知道，有些事，再努力也没用。', en: 'The meaning of effort is to let you know that some things are useless no matter how hard you try.' },
    { category: 'Disillusioned', cn: '我以为时间会让我忘记，结果只是让我习惯了痛苦。', en: 'I thought time would make me forget, but it just made me get used to the pain.' },
    { category: 'Disillusioned', cn: '生活的Bug从来不会修复，只会越积越多，压垮你。', en: 'Life\'s bugs are never fixed; they only accumulate more and more, crushing you.' },
    { category: 'Disillusioned', cn: '所谓的幸运，不过是别人不屑一顾的剩余。', en: 'The so-called luck is just the leftover that others disdain.' },
    { category: 'Disillusioned', cn: '你越是挣扎，就越被生活捆得越紧。', en: 'The more you struggle, the tighter life binds you.' },
    { category: 'Disillusioned', cn: '有些人不是没能力，是没机会，而机会，从来不属于普通人。', en: 'Some people are not incompetent; they just have no chance, and chances never belong to ordinary people.' },
    { category: 'Disillusioned', cn: '我以为我在拯救自己，结果只是把自己推向更深的深渊。', en: 'I thought I was saving myself, but I was just pushing myself into a deeper abyss.' },
    { category: 'Disillusioned', cn: '深情一文不值，新鲜感才是成年人的通行证。', en: 'Deep affection is worthless; freshness is the pass for adults.' },
    { category: 'Disillusioned', cn: '你拼尽全力去迎合，最后还是活成了别人不喜欢的样子。', en: 'You try your best to cater, but in the end, you still live like someone others don\'t like.' },
    { category: 'Disillusioned', cn: '生活没有奇迹，只有你自欺欺人的侥幸。', en: 'There are no miracles in life, only your self-deceptive fluke.' },
    { category: 'Disillusioned', cn: '所谓的懂事，就是压抑自己的情绪，成全别人的舒服。', en: 'The so-called sensible is to suppress your own emotions to make others comfortable.' },
    { category: 'Disillusioned', cn: '努力了一辈子，最后发现，不过是为别人做了嫁衣。', en: 'After working hard all your life, you finally find that you are just making wedding clothes for others.' },
    { category: 'Disillusioned', cn: '我以为我能改变世界，结果连自己都改变不了。', en: 'I thought I could change the world, but I couldn\'t even change myself.' },
    { category: 'Disillusioned', cn: '有些人不是不珍惜，是根本不懂什么叫珍惜，也不想懂。', en: 'Some people don\'t not cherish; they just don\'t understand what cherishing is, and don\'t want to understand.' },
    { category: 'Disillusioned', cn: '自由从来都是奢侈品，你连喘息的资格都没有，何谈自由。', en: 'Freedom has always been a luxury; you don\'t even have the right to breathe, let alone freedom.' },
    { category: 'Disillusioned', cn: '你越善良，越容易被欺负；越真诚，越容易被伤害。', en: 'The kinder you are, the easier you are to be bullied; the more sincere you are, the easier you are to be hurt.' },
    { category: 'Disillusioned', cn: '生活的真相：不是你不够好，是你再好，也没人在意。', en: 'The truth of life: it\'s not that you\'re not good enough, but no one cares how good you are.' },
    { category: 'Disillusioned', cn: '所谓的梦想，不过是让你在底层挣扎时，多一个借口。', en: 'The so-called dream is just an excuse for you to struggle at the bottom.' },
    { category: 'Disillusioned', cn: '我以为熬到终点就有惊喜，结果终点只有绝望在等我。', en: 'I thought there would be a surprise when I reached the end, but only despair was waiting for me at the end.' },
    { category: 'Disillusioned', cn: '有些人不是不努力，是努力的方向，从一开始就错了。', en: 'Some people are not unmotivated; the direction of their efforts was wrong from the beginning.' },
    { category: 'Disillusioned', cn: '你付出的所有努力，都抵不过别人一句“我有关系”。', en: 'All the efforts you put in are not worth others saying "I have connections".' },
    { category: 'Disillusioned', cn: '时间不会治愈你，只会让你习惯，习惯被伤害，习惯不被爱。', en: 'Time won\'t heal you; it will only make you get used to being hurt and not being loved.' },
    { category: 'Disillusioned', cn: '所谓的朋友，不过是你有用时靠近，你没用时远离。', en: 'The so-called friends are just people who approach you when you are useful and stay away when you are not.' },
    { category: 'Disillusioned', cn: '你越想抓住什么，就越容易失去什么，无一例外。', en: 'The more you want to hold on to something, the easier it is to lose it, without exception.' },
    { category: 'Disillusioned', cn: '努力的意义，就是证明自己，真的不行。', en: 'The meaning of effort is to prove that you really can\'t do it.' },
    { category: 'Disillusioned', cn: '我以为我很坚强，原来只是没经历过真正的绝望。', en: 'I thought I was strong, but it turns out I just haven\'t experienced real despair.' },
    { category: 'Disillusioned', cn: '生活没有偏爱，只有偏爱那些不需要偏爱的人。', en: 'Life has no preference; it only favors those who don\'t need preference.' },
    { category: 'Disillusioned', cn: '有些人不是不爱，是爱不起，也配不上。', en: 'Some people don\'t stop loving; they can\'t afford to love, and don\'t deserve it.' },
    { category: 'Disillusioned', cn: '你掏心掏肺的付出，最后换来的，都是得寸进尺。', en: 'All the wholehearted efforts you give will eventually be met with greed.' },
    { category: 'Disillusioned', cn: '所谓的成长，就是把哭声调成静音，把情绪藏进心底。', en: 'The so-called growth is to turn the cry to silent and hide emotions in the bottom of the heart.' },
    { category: 'Disillusioned', cn: '我以为我能逃离，结果只是从一个火坑，跳进另一个火坑。', en: 'I thought I could escape, but I just jumped from one pit of fire to another.' },
    { category: 'Disillusioned', cn: '努力不一定能成功，但不努力，一定不会失败，因为你连失败的资格都没有。', en: 'Effort doesn\'t necessarily lead to success, but not trying will definitely not lead to failure, because you don\'t even have the right to fail.' },
    { category: 'Disillusioned', cn: '生活的Bug，从来不会眷顾任何人，你越弱小，它越嚣张。', en: 'Life\'s bugs never favor anyone; the weaker you are, the more arrogant they are.' },
    { category: 'Disillusioned', cn: '有些人不是不明白，是明白太晚，一切都无法挽回。', en: 'Some people are not ununderstanding; they understand too late, and everything is irreversible.' },
    { category: 'Disillusioned', cn: '你以为的希望，不过是命运给你画的大饼，永远吃不到。', en: 'The hope you think is just a pie drawn by fate, which you will never eat.' },
    { category: 'Disillusioned', cn: '所谓的公平，不过是弱者的自我安慰，强者的游戏规则。', en: 'The so-called fairness is just self-consolation for the weak and a game rule for the strong.' },
    { category: 'Disillusioned', cn: '我以为时间会给我答案，结果时间只给了我更多的疑问。', en: 'I thought time would give me answers, but time only gave me more questions.' },
    { category: 'Disillusioned', cn: '你越努力，越发现，自己不过是别人棋盘上的一颗棋子。', en: 'The harder you work, the more you find that you are just a chess piece on others\' chessboard.' },
    { category: 'Disillusioned', cn: '善良是软肋，真诚是枷锁，越善良，越难前行。', en: 'Kindness is a weakness, sincerity is a shackle; the kinder you are, the harder it is to move forward.' },
    { category: 'Disillusioned', cn: '有些人不是不努力，是努力了，也赶不上别人的与生俱来。', en: 'Some people are not unmotivated; even if they work hard, they can\'t catch up with others\' inborn advantages.' },
    { category: 'Disillusioned', cn: '生活没有惊喜，只有惊吓，一次比一次狠。', en: 'There are no surprises in life, only scares, getting worse every time.' },
    { category: 'Disillusoned', cn: '所谓的坚持，不过是不甘心，不甘心自己的努力白费。', en: 'The so-called persistence is just unwillingness, unwillingness that your efforts are in vain.' },
    { category: 'Disillusioned', cn: '我以为我能改变别人，结果只是被别人改变，变得面目全非。', en: 'I thought I could change others, but I was just changed by others, becoming unrecognizable.' },
    { category: 'Disillusioned', cn: '你越迁就别人，别人就越不把你当回事，这是人性。', en: 'The more you accommodate others, the less they take you seriously; this is human nature.' },
    { category: 'Disillusioned', cn: '努力的意义，就是让你看清现实，现实有多残酷，你就有多渺小。', en: 'The meaning of effort is to let you see the reality clearly; the crueler the reality, the smaller you are.' },
    { category: 'Disillusioned', cn: '时间不是解药，是毒药，慢慢侵蚀你所有的期待。', en: 'Time is not an antidote, but a poison, slowly eroding all your expectations.' },
    { category: 'Disillusioned', cn: '有些人不是不珍惜，是珍惜的不是你，从来都不是。', en: 'Some people don\'t not cherish; what they cherish is not you, never you.' },
    { category: 'Disillusioned', cn: '你以为的自由，不过是别人施舍的怜悯，随时可以收回。', en: 'The freedom you think is just the mercy given by others, which can be taken back at any time.' },
    { category: 'Disillusioned', cn: '生活的真相：你越想变好，就越难变好，阻碍从来不会缺席。', en: 'The truth of life: the more you want to get better, the harder it is to get better; obstacles will never be absent.' },
    { category: 'Disillusioned', cn: '所谓的梦想，不过是你逃避现实的借口，自欺欺人罢了。', en: 'The so-called dream is just an excuse for you to escape reality, self-deception.' },
    { category: 'Disillusioned', cn: '我以为熬过去就是晴天，结果熬过去，还是阴雨天。', en: 'I thought getting through it would be sunny, but after getting through it, it\'s still rainy.' },
    { category: 'Disillusioned', cn: '有些人不是不努力，是努力错了对象，竹篮打水一场空。', en: 'Some people are not unmotivated; they worked hard on the wrong target, getting nothing in the end.' },
    { category: 'Disillusioned', cn: '你付出的所有真心，都被当成理所当然，一文不值。', en: 'All the sincerity you gave is taken for granted, worth nothing.' },
    { category: 'Disillusioned', cn: '所谓的朋友，不过是利益的结合体，没有利益，寸步难行。', en: 'The so-called friends are just a combination of interests; without interests, it\'s impossible to move forward.' },
    { category: 'Disillusioned', cn: '你越坚强，越没人疼；越脆弱，越没人管，这就是现实。', en: 'The stronger you are, the less someone cares about you; the more vulnerable you are, the less someone cares about you. This is reality.' },
    { category: 'Disillusioned', cn: '努力不一定能改变命运，但能让你更清楚地认识到，命运早已注定。', en: 'Effort doesn\'t necessarily change fate, but it can make you more clearly realize that fate is already destined.' },
    { category: 'Disillusioned', cn: '我以为我能拥有一切，结果连一无所有，都成了奢望。', en: 'I thought I could have everything, but even having nothing has become a luxury.' },
    { category: 'Disillusioned', cn: '生活没有退路，你只能硬着头皮往前走，哪怕前方是悬崖。', en: 'Life has no retreat; you can only move forward bravely, even if there is a cliff ahead.' },
    { category: 'Disillusioned', cn: '有些人不是不优秀，是优秀得不合时宜，被世界抛弃。', en: 'Some people are not unexcellent; they are excellent at the wrong time, abandoned by the world.' },
    { category: 'Disillusioned', cn: '所谓的成长，就是学会接受，接受自己的平庸，接受现实的残酷。', en: 'The so-called growth is to learn to accept, accept your own mediocrity, and accept the cruelty of reality.' },
    { category: 'Disillusioned', cn: '你越想抓住幸福，幸福就越容易溜走，就像沙握在手里。', en: 'The more you want to hold happiness, the easier it is to slip away, just like sand in your hand.' },
    { category: 'Disillusioned', cn: '努力的意义，就是让你知道，有些差距，永远无法弥补。', en: 'The meaning of effort is to let you know that some gaps can never be made up.' },
    { category: 'Disillusioned', cn: '我以为时间会抚平伤口，结果伤口只是结了痂，一碰就疼。', en: 'I thought time would heal the wound, but the wound only scabbed and hurts when touched.' },
    { category: 'Disillusioned', cn: '生活的Bug，从来不会给你修复的机会，只会让你一错再错。', en: 'Life\'s bugs never give you a chance to fix them; they only make you make mistakes again and again.' },
    { category: 'Disillusioned', cn: '有些人不是不珍惜，是他们的珍惜，太廉价，一文不值。', en: 'Some people don\'t not cherish; their cherishing is too cheap, worth nothing.' },
    { category: 'Disillusioned', cn: '你以为的逆袭，不过是命运的玩笑，笑完之后，还是原地踏步。', en: 'The counterattack you think is just a joke of fate; after laughing, you still stay in place.' },
    { category: 'Disillusioned', cn: '所谓的公平，就是你努力十年，不如别人出生就拥有。', en: 'The so-called fairness is that you work hard for ten years, not as good as what others have at birth.' },
    { category: 'Disillusioned', cn: '我以为我能逃离孤独，结果孤独就像影子，形影不离。', en: 'I thought I could escape loneliness, but loneliness is like a shadow, never leaving.' },
    { category: 'Disillusioned', cn: '你越善良，越容易被利用；越真诚，越容易被背叛。', en: 'The kinder you are, the easier you are to be used; the more sincere you are, the easier you are to be betrayed.' },
    { category: 'Disillusioned', cn: '生活没有奇迹，只有你自欺欺人的自我安慰。', en: 'There are no miracles in life, only your self-deceptive self-consolation.' },
    { category: 'Disillusioned', cn: '所谓的梦想，不过是你年轻时的幻想，长大后，只剩无奈。', en: 'The so-called dream is just your fantasy when you are young; when you grow up, only helplessness remains.' },
    { category: 'Disillusioned', cn: '我以为熬到尽头就有希望，结果尽头，还是无尽的煎熬。', en: 'I thought there would be hope at the end, but the end is still endless suffering.' },
    { category: 'Disillusioned', cn: '有些人不是不努力，是努力了，也得不到别人的认可。', en: 'Some people are not unmotivated; even if they work hard, they can\'t get others\' recognition.' },
    { category: 'Disillusioned', cn: '你付出的所有努力，都抵不过别人的一句敷衍。', en: 'All the efforts you put in are not worth others\' perfunctory words.' },
    { category: 'Disillusioned', cn: '时间不会让你忘记痛苦，只会让你麻木，麻木到感觉不到痛苦。', en: 'Time won\'t make you forget the pain; it will only make you numb, so numb that you can\'t feel the pain.' },
    { category: 'Disillusioned', cn: '所谓的朋友，不过是你需要时不在，你不需要时出现。', en: 'The so-called friends are just people who are not there when you need them, but appear when you don\'t.' },
    { category: 'Disillusioned', cn: '你越迁就，越卑微；越卑微，越被轻视，这就是人性的真相。', en: 'The more you accommodate, the more humble you are; the more humble you are, the more you are despised. This is the truth of human nature.' },
    { category: 'Disillusioned', cn: '努力的意义，就是让你看清自己，看清自己有多渺小，有多无力。', en: 'The meaning of effort is to let you see yourself clearly, see how small and powerless you are.' },
    { category: 'Disillusioned', cn: '我以为我能改变生活，结果生活改变了我，变得我都不认识自己。', en: 'I thought I could change life, but life changed me, making me unrecognizable to myself.' },
    { category: 'Disillusioned', cn: '生活没有彩蛋，只有不断的意外，一次比一次残酷。', en: 'Life has no Easter eggs, only constant accidents, getting crueler every time.' },
    { category: 'Disillusioned', cn: '有些人不是不珍惜，是他们根本不知道，什么是值得珍惜的。', en: 'Some people don\'t not cherish; they just don\'t know what is worth cherishing.' },
    { category: 'Disillusioned', cn: '你以为的自由，不过是你自我欺骗的假象，根本不存在。', en: 'The freedom you think is just an illusion of your self-deception; it doesn\'t exist at all.' },
    { category: 'Disillusioned', cn: '所谓的成长，就是把所有的情绪，都藏在心底，笑着说没事。', en: 'The so-called growth is to hide all emotions in the bottom of the heart and smile and say it\'s okay.' },
    { category: 'Disillusioned', cn: '我以为我能拥有幸福，结果幸福从来都不属于我，从未属于过。', en: 'I thought I could have happiness, but happiness has never belonged to me, never.' },
    { category: 'Disillusioned', cn: '生活的真相：你越努力，越不幸；越平凡，越安稳，却越不甘。', en: 'The truth of life: the harder you work, the more unfortunate you are; the more ordinary you are, the more stable you are, but the more unwilling you are.' },
    { category: 'Disillusioned', cn: '有些人不是不努力，是努力的尽头，还是一无所有。', en: 'Some people are not unmotivated; the end of their efforts is still nothing.' },
    { category: 'Disillusioned', cn: '你掏心掏肺的对待，最后换来的，都是背叛和伤害。', en: 'All the wholehearted treatment you give will eventually be met with betrayal and hurt.' },
    { category: 'Disillusioned', cn: '所谓的希望，不过是让你多熬一会儿，多受一会儿苦。', en: 'The so-called hope is just to let you endure a little longer and suffer a little more.' },
    { category: 'Disillusioned', cn: '我以为时间会给我公平，结果时间只给了我不公，一次又一次。', en: 'I thought time would give me fairness, but time only gave me injustice, again and again.' },
    { category: 'Disillusioned', cn: '生活没有退路，只有往前走，哪怕前方是万丈深渊，也别无选择。', en: 'Life has no retreat; you can only move forward, even if there is an abyss ahead, you have no choice.' },
    { category: 'Disillusioned', cn: '所谓的希望，不过是让你多熬一会儿，多受一会儿苦。', en: 'The so-called hope is just to let you endure a little longer and suffer a little more.' },
    { category: 'Disillusioned', cn: '我以为时间会给我公平，结果时间只给了我不公，一次又一次。', en: 'I thought time would give me fairness, but time only gave me injustice, again and again.' },
    { category: 'Disillusioned', cn: '生活没有退路，只有往前走，哪怕前方是万丈深渊，也别无选择。', en: 'Life has no retreat; you can only move forward, even if there is an abyss ahead, you have no choice.' },
    { category: 'Disillusioned', cn: '努力了那么久，最后还是输给了无能为力。', en: 'I tried so hard, yet in the end, I lost to powerlessness.' },
    { category: 'Disillusioned', cn: '满心欢喜的开始，最后都变成了遍体鳞伤的结束。', en: 'Joyful beginnings always turn into scarred endings.' },
    { category: 'Disillusioned', cn: '原来有些难过，是连眼泪都懒得流的疲惫。', en: 'Some sorrows are just tiredness that even tears refuse to shed.' },
    { category: 'Disillusioned', cn: '我什么都抓不住，连快乐都从我指缝溜走。', en: 'I can hold onto nothing, not even happiness slips through my fingers.' },
    { category: 'Disillusioned', cn: '熬得住出众，熬不住出局，可我连熬的力气都快没了。', en: 'Endure to shine, give up to lose, but I barely have the strength to keep going.' },
    { category: 'Disillusioned', cn: '所有的热情，都在一次次失望里慢慢熄灭。', en: 'All passion slowly dies out in repeated disappointments.' },
    { category: 'Disillusioned', cn: '表面笑着没事，心里早已溃不成军。', en: 'I smile and say I’m fine, but my heart is already in ruins.' },
    { category: 'Disillusioned', cn: '后来我什么都明白了，只是什么都晚了。', en: 'Later I understood everything, only it was all too late.' },
    { category: 'Disillusioned', cn: '生活从来都不会善待敏感又心软的人。', en: 'Life never treats the sensitive and soft-hearted well.' },
    { category: 'Disillusioned', cn: '我好像一直在放弃，又好像一直在等待。', en: 'I seem to be giving up, yet also waiting all the time.' },
    { category: 'Disillusioned', cn: '满心期待，换来的不过是一场空欢喜。', en: 'Full of expectation, only to get nothing but empty joy.' },
    { category: 'Disillusioned', cn: '不是不想快乐，是快乐根本绕不开我。', en: 'It’s not that I don’t want happiness, it just never comes to me.' },
    { category: 'Disillusioned', cn: '很多事情，我尽力了，也只能这样了。', en: 'For many things, I tried my best, and that’s all there is.' },
    { category: 'Disillusioned', cn: '成长原来是一场不断失去的旅程。', en: 'Growing up turns out to be a journey of constant loss.' },
    { category: 'Disillusioned', cn: '我好像谁都留不住，也什么都得不到。', en: 'I can keep no one, and gain nothing.' },
    { category: 'Disillusioned', cn: '连崩溃都要选好时间，怕打扰别人，也怕自己难堪。', en: 'Even breakdowns need timing, fearing to disturb others and embarrass myself.' },
    { category: 'Disillusioned', cn: '后来我不再期待，也就不再受伤。', en: 'Later I stopped expecting, so I stopped getting hurt.' },
    { category: 'Disillusioned', cn: '生活给了我很多选择，我却一个都选不对。', en: 'Life gave me many choices, yet I never pick the right one.' },
    { category: 'Disillusioned', cn: '所有的道理我都懂，可情绪就是不听话。', en: 'I know all the truths, but my emotions just won’t listen.' },
    { category: 'Disillusioned', cn: '我假装坚强，只是不想让人看见我的狼狈。', en: 'I pretend to be strong, just not to let others see my mess.' },
    { category: 'Disillusioned', cn: '原来最痛的不是失去，是从未真正拥有。', en: 'The worst pain is not losing, but never truly having.' },
    { category: 'Disillusioned', cn: '我撑了一天又一天，不知道还能撑多久。', en: 'I hold on day after day, not knowing how much longer I can.' },
    { category: 'Disillusioned', cn: '世界很热闹，可我始终是一个人。', en: 'The world is lively, but I am always alone.' },
    { category: 'Disillusioned', cn: '有些委屈，除了自己谁也不能说。', en: 'Some grievances can be told to no one but myself.' },
    { category: 'Disillusioned', cn: '慢慢的，我不再对任何人抱有希望。', en: 'Gradually, I no longer hope for anyone.' },
    { category: 'Disillusioned', cn: '努力不一定有结果，不努力一定很轻松。', en: 'Effort may not pay off, but no effort is definitely easier.' },
    { category: 'Disillusioned', cn: '我好像在放弃你，又好像在等你。', en: 'I seem to be letting you go, yet also waiting for you.' },
    { category: 'Disillusioned', cn: '人生这趟旅途，满是遗憾和错过。', en: 'This journey of life is full of regrets and misses.' },
    { category: 'Disillusioned', cn: '我什么都不想要了，包括我自己。', en: 'I want nothing anymore, not even myself.' },
    { category: 'Disillusioned', cn: '所有的温柔，都在冷漠里慢慢消失。', en: 'All gentleness fades away in coldness.' },
    { category: 'Disillusioned', cn: '后来我习惯了失望，也就不再难过。', en: 'Later I got used to disappointment, so I no longer feel sad.' },
    { category: 'Disillusioned', cn: '生活总是在我快要好起来的时候，给我一巴掌。', en: 'Life always slaps me when I’m about to get better.' },
    { category: 'Disillusioned', cn: '我好像被困在原地，走不出去也回不去。', en: 'I seem stuck, unable to move forward or go back.' },
    { category: 'Disillusioned', cn: '原来真心换真心，只是我一厢情愿。', en: 'Sincerity for sincerity was just my wishful thinking.' },
    { category: 'Disillusioned', cn: '我耗尽了所有温柔，只换来一身疲惫。', en: 'I exhausted all my tenderness, only to get exhaustion.' },
    { category: 'Disillusioned', cn: '没人懂我的欲言又止，没人懂我的沉默。', en: 'No one understands my unspoken words, no one understands my silence.' },
    { category: 'Disillusioned', cn: '我努力笑着，可心里早已一片荒芜。', en: 'I try to smile, but my heart is already a wasteland.' },
    { category: 'Disillusioned', cn: '有些关系，断了舍不得，继续又太累。', en: 'Some relationships are hard to let go, yet tiring to keep.' },
    { category: 'Disillusioned', cn: '我以为坚持就会有转机，现实却一次次打脸。', en: 'I thought persistence would change things, but reality slaps me repeatedly.' },
    { category: 'Disillusioned', cn: '到最后才发现，自己什么都不是。', en: 'In the end, I realize I mean nothing.' },
    { category: 'Disillusioned', cn: '难过归难过，生活还是要继续。', en: 'Sad as I am, life still goes on.' },
    { category: 'Disillusioned', cn: '我把快乐丢了，再也找不回来了。', en: 'I lost my happiness and can never find it back.' },
    { category: 'Disillusioned', cn: '所有的离开，都是蓄谋已久。', en: 'All departures are long premeditated.' },
    { category: 'Disillusioned', cn: '我连情绪都要克制，活的小心翼翼。', en: 'I even restrain my emotions, living cautiously.' },
    { category: 'Disillusioned', cn: '后来我不再争辩，懂我的人自然懂。', en: 'Later I stopped arguing; those who understand will understand.' },
    { category: 'Disillusioned', cn: '人生看似有很多可能，其实早已注定。', en: 'Life seems full of possibilities, yet it is already destined.' },
    { category: 'Disillusioned', cn: '我什么都扛着，最后却没人在乎。', en: 'I bear everything alone, yet no one cares in the end.' },
    { category: 'Disillusioned', cn: '原来最孤独的，是人群中的沉默。', en: 'The loneliest thing is silence in the crowd.' },
    { category: 'Disillusioned', cn: '我等了很久，最后什么都没等到。', en: 'I waited for a long time, and got nothing in the end.' },
    { category: 'Disillusioned', cn: '热情这东西，耗尽了就再也没有了。', en: 'Once passion is exhausted, it never comes back.' },
    { category: 'Disillusioned', cn: '生活总是让懂事的人，承受更多。', en: 'Life always makes sensible people bear more.' },
    { category: 'Disillusioned', cn: '我好像在治愈自己，又好像在慢慢崩溃。', en: 'I seem to be healing myself, yet also breaking down slowly.' },
    { category: 'Disillusioned', cn: '所有的承诺，最后都变成了笑话。', en: 'All promises turn into jokes in the end.' },
    { category: 'Disillusioned', cn: '我习惯了一个人，也习惯了不被爱。', en: 'I am used to being alone, and also used to not being loved.' },
    { category: 'Disillusioned', cn: '不是所有事情，努力了就有用。', en: 'Not everything works out just by trying.' },
    { category: 'Disillusioned', cn: '我把所有委屈咽下去，换来一句懂事。', en: 'I swallow all grievances, only to be called sensible.' },
    { category: 'Disillusioned', cn: '后来我不再期待任何人，也不再依赖任何人。', en: 'Later I no longer expect or rely on anyone.' },
    { category: 'Disillusioned', cn: '生活给我的，从来都不是我想要的。', en: 'What life gives me is never what I want.' },
    { category: 'Disillusioned', cn: '我好像什么都有，又好像什么都没有。', en: 'I seem to have everything, yet also have nothing.' },
    { category: 'Disillusioned', cn: '有些伤痛，时间根本治愈不了。', en: 'Some pains can never be healed by time.' },
    { category: 'Disillusioned', cn: '我假装无所谓，其实心早已碎了。', en: 'I pretend it doesn’t matter, but my heart is already broken.' },
    { category: 'Disillusioned', cn: '人生到最后，都是一场空。', en: 'In the end, life is all in vain.' },
    { category: 'Disillusioned', cn: '我努力讨好所有人，却唯独委屈了自己。', en: 'I try to please everyone, yet only wrong myself.' },
    { category: 'Disillusioned', cn: '原来成年人的世界，连崩溃都要静音。', en: 'In the adult world, even breakdowns must be silent.' },
    { category: 'Disillusioned', cn: '我走了很远的路，最后还是回到原点。', en: 'I walked a long way, only to return to the start.' },
    { category: 'Disillusioned', cn: '所有的温柔，都被现实磨平了棱角。', en: 'All gentleness is smoothed by reality.' },
    { category: 'Disillusioned', cn: '我好像被世界遗忘，无人问津。', en: 'I seem forgotten by the world, ignored by all.' },
    { category: 'Disillusioned', cn: '不是不想哭，是哭了也没用。', en: 'It’s not that I don’t want to cry, but crying is useless.' },
    { category: 'Disillusioned', cn: '后来我学会了沉默，因为说了也没人懂。', en: 'Later I learned to be silent, for no one understands.' },
    { category: 'Disillusioned', cn: '生活总是在为难心软的人。', en: 'Life always torments the soft-hearted.' },
    { category: 'Disillusioned', cn: '我耗尽了所有期待，只剩下麻木。', en: 'I exhausted all expectations, only numbness remains.' },
    { category: 'Disillusioned', cn: '原来很多关系，走着走着就散了。', en: 'Many relationships just fall apart along the way.' },
    { category: 'Disillusioned', cn: '我什么都不想争，也什么都不想要。', en: 'I don’t want to fight for anything, nor want anything.' },
    { category: 'Disillusioned', cn: '人生很多事，不是我能控制的。', en: 'Many things in life are beyond my control.' },
    { category: 'Disillusioned', cn: '我表面平静，内心早已翻江倒海。', en: 'I look calm, but my heart is in turmoil.' },
    { category: 'Disillusioned', cn: '所有的美好，都只是短暂的假象。', en: 'All beauty is just a brief illusion.' },
    { category: 'Disillusioned', cn: '我等的不是结果，是慢慢死心的过程。', en: 'I’m not waiting for a result, but for the slow death of hope.' },
    { category: 'Disillusioned', cn: '生活从来都不容易，只是我习惯了硬撑。', en: 'Life is never easy; I just get used to holding on.' },
    { category: 'Disillusioned', cn: '原来真心，在现实面前一文不值。', en: 'Sincerity is worthless in front of reality.' },
    { category: 'Disillusioned', cn: '我好像一直在失去，从未真正拥有。', en: 'I seem to be losing all the time, never truly having.' },
    { category: 'Disillusioned', cn: '连快乐都显得那么奢侈。', en: 'Even happiness seems so luxurious.' },
    { category: 'Disillusioned', cn: '我努力了，可生活还是不放过我。', en: 'I tried, but life still won’t let me go.' },
    { category: 'Disillusioned', cn: '后来我不再表达情绪，学会了自我消化。', en: 'Later I stopped expressing emotions and learned to digest them alone.' },
    { category: 'Disillusioned', cn: '人生这趟车，有人上车，有人下车，没人陪我到终点。', en: 'On life’s train, people come and go; no one stays till the end.' },
    { category: 'Disillusioned', cn: '我什么都明白，可就是走不出来。', en: 'I understand everything, yet just can’t get out.' },
    { category: 'Disillusioned', cn: '所有的安全感，都是自己给自己的假象。', en: 'All sense of security is just an illusion I give myself.' },
    { category: 'Disillusioned', cn: '我好像被生活困住，动弹不得。', en: 'I seem trapped by life, unable to move.' },
    { category: 'Disillusioned', cn: '后来我不再相信任何人，包括我自己。', en: 'Later I no longer trust anyone, not even myself.' },
    { category: 'Disillusioned', cn: '难过到极致，反而没有眼泪。', en: 'When sadness reaches the extreme, there are no tears.' },
    { category: 'Disillusioned', cn: '我努力活成别人期待的样子，却丢了自己。', en: 'I try to live as others expect, yet lose myself.' },
    { category: 'Disillusioned', cn: '生活没有答案，只有无尽的煎熬。', en: 'Life has no answers, only endless suffering.' },
    { category: 'Disillusioned', cn: '我好像在等待一场不会来的救赎。', en: 'I seem to wait for a salvation that will never come.' },
    { category: 'Disillusioned', cn: '所有的坚持，最后都变成了笑话。', en: 'All persistence turns into a joke in the end.' },
    { category: 'Disillusioned', cn: '我习惯了失望，也就不再期待。', en: 'I got used to disappointment, so I no longer expect.' },
    { category: 'Disillusioned', cn: '人生到最后，只剩自己和一地鸡毛。', en: 'In the end, life leaves only me and a mess.' },
    { category: 'Disillusioned', cn: '我什么都扛不住了，却还要继续扛。', en: 'I can’t bear it anymore, yet I still have to.' },
    // [Deeply Relatable]
    { category: 'Deeply Relatable', cn: '谁心里没点伤？只是我把它封装得比较好。', en: 'Who doesn\'t have wounds? I just encapsulated mine well.' },
    { category: 'Deeply Relatable', cn: '晚上的风很大，像极了我在职场里的卑微。', en: 'The wind at night is strong, just like my humility in the workplace.' },
    { category: 'Deeply Relatable', cn: '有时候，关掉电脑才是真正的下班。', en: 'Sometimes, turning off the computer is the only true way to clock out.' },
    { category: 'Deeply Relatable', cn: '我们都在用忙碌，来掩盖灵魂的荒芜。', en: 'We all use busyness to cover the desolation of our souls.' },
    { category: 'Deeply Relatable', cn: '所谓的合群，不过是学会了在特定频率下伪装。', en: 'Fitting in is just learning how to disguise yourself at certain frequencies.' },
    { category: 'Deeply Relatable', cn: '我也想做个小孩，可世界只想要个能干活的 API。', en: 'I want to be a child, but the world just wants a working API.' },
    { category: 'Deeply Relatable', cn: '心酸的是，我不仅没赢，连输的姿势都不够好看。', en: 'The sad thing is, I didn\'t win, and even my losing posture wasn\'t pretty enough.' },
    { category: 'Deeply Relatable', cn: '那些深夜里流过的泪，都是白天没能说出口的拒绝。', en: 'Tears shed late at night are the refusals I couldn\'t voice during the day.' },
    { category: 'Deeply Relatable', cn: '我在人群里拼命点头，心里却一直在抛出 401。', en: 'I nod frantically in the crowd, while my heart keeps throwing a 401.' },
    { category: 'Deeply Relatable', cn: '最深的情绪，往往都在没有日志记录的私有作用域里。', en: 'The deepest emotions are usually in private scopes with no logging.' },
    { category: 'Deeply Relatable', cn: '生活不是电影，它没有完美的配乐和剪辑。', en: 'Life is not a movie; it lacks perfect soundtracks and editing.' },
    { category: 'Deeply Relatable', cn: '我只是累了，连更新状态码的力气都没有。', en: 'I\'m just tired, with no strength left even to update my status code.' },
    // [Sad & Hilarious - 伤感搞笑大补充]
    { category: 'Sad & Hilarious', cn: '比起单身，我更怕我的 GitHub 绿墙变白。', en: 'I fear my GitHub contribution wall turning white more than being single.' },
    { category: 'Sad & Hilarious', cn: '别问我为什么哭，问就是眼睛进了 JavaScript。', en: 'Don\'t ask why I\'m crying; ask why JavaScript got in my eyes.' },
    { category: 'Sad & Hilarious', cn: '我的存折像个递归函数，一直减到基础情况：0。', en: 'My savings account is like a recursive function, reducing to the base case: 0.' },
    { category: 'Sad & Hilarious', cn: '我以为我有对象，原来那只是个 Object。', en: 'I thought I had a partner; turns out it was just an Object.' },
    { category: 'Sad & Hilarious', cn: '我的心情像现在的汇率，跌得没完没了。', en: 'My mood is like the current exchange rate: an endless drop.' }
]);
